#!/usr/bin/env node

var nemesis = require('./');
var argv = require('yargs')
  .usage('nemesis {command} --regions "us-east-1" "us-west-2" --group "group_name" --launch-config "launch_config" [--spot-group "spot_group"]')
  .demand(1)
  .command('command', 'Can be one of: replace')
  .alias('r', 'regions')
  .alias('g', 'group')
  .alias('l', 'launch-config')
  .alias('s', 'spot-group')
  .array('r')
  .demand(['regions', 'group', 'launch-config'])
  .help('h')
  .alias('h', 'help')
  .argv;

switch(argv._[0]) {
  case 'replace':
    nemesis.replace(
      argv['regions'],
      argv['group'],
      argv['launch-config']
    ).then(function(result){
      console.log('Update complete');
      process.exit(0);
    }).catch(function(err){
      console.error(err);
      process.exit(1);
    });
    break;
  default:
    console.log('Unrecognized command: "%s"', argv._[0]);
    process.exit(1);
}
